variables:
  GOPATH: "/workspace"
  REPO: github.com/mikechris/kaha/clickhouse

stages:
  - docker
  - build

build-docker-image:
  stage: docker
  tags:
  - docker-build
  script:
  - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME .

build-golang-1.9:
  stage: build
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME 
  tags:
    - docker-build
  script:
    - export GOPATH=$GOPATH
    - mkdir -p $GOPATH/src/$REPO
    - cd $GOPATH/src/$REPO
    - ln -s $CI_PROJECT_DIR .
    - cd $CI_PROJECT_NAME
    - go build
  artifacts:
    paths:
      - kaha
    expire_in: 1 day